
// AUTH
export const FETCH_LOGIN 			= 'FETCH_LOGIN';
export const RECEIVE_LOGIN 			= 'RECEIVE_LOGIN';
export const UPDATE_FIELD_AUTH 		= 'UPDATE_FIELD_AUTH';
export const FETCH_REGISTER_USER 	= 'FETCH_REGISTER_USER';
export const RECEIVE_REGISTER_USER 	= 'RECEIVE_REGISTER_USER';

/// WORK SPACE
export const FETCH_ALL_TODOS 		= 'FETCH_ALL_TODOS';
export const RECEIVE_ALL_TODOS 		= 'RECEIVE_ALL_TODOS';

export const FETCH_CREATE_TODO 		= 'FETCH_CREATE_TODO';
export const RECEIVE_CREATE_TODO 	= 'RECEIVE_CREATE_TODO';

export const UPDATE_FIELD_NEW_TODO 	= 'UPDATE_FIELD_NEW_TODO';


// TODO LIST
export const FETCH_DELETE_TODO 		= 'FETCH_DELETE_TODO';
export const RECEIVE_DELETE_TODO 	= 'RECEIVE_DELETE_TODO';

export const FETCH_EDIT_TODO 		= 'FETCH_EDIT_TODO';
export const RECEIVE_EDIT_TODO 		= 'RECEIVE_EDIT_TODO';

export const FETCH_TOGGLE_TODO 		= 'FETCH_TOGGLE_TODO';
export const RECEIVE_TOGGLE_TODO 	= 'RECEIVE_TOGGLE_TODO';

export const UPDATE_FIELD_EDIT_TODO = 'UPDATE_FIELD_EDIT_TODO';